version:
services:
  build:
    context:
    dockerfile:
    args:
  image:
  command:
  entrypoint:
  container_name:
  links:
  volumes_from:
  volumes:
  volume_driver: 
  tmpfs:
  expose:
  ports:
  net:
  network_mode:
  networks:
  deploy:
    placement:
    replicas:
    mode:
    update_config:
    resources:
    restart_policy:
    labels:
  labels: 
  devices: 
  read_only: 
  healthcheck:
    test:
    interval:
    timeout:
    retries:
    disable:
  env_file:
  environment: 
  secrets: 
  cpu_shares: 
  cpu_quota: 
  cpuset: 
  domainname: 
  hostname: 
  ipc: 
  mac_address: 
  mem_limit: 
  memswap_limit: 
  privileged: 
  shm_size: 
  depends_on: 
  extends: 
  external_links: 
  stdin_open: 
  user: 
  working_dir: 
  extra_hosts: 
  restart: 
  ulimits: 
  tty: 
  dns: 
  dns_search: 
  pid: 
  security_opt: 
  cap_add: 
  cap_drop: 
  cgroup_parent: 
  logging: 
  log_driver: 
  log_opt: 
  stopsignal: 
  stop_signal: 
  stop_grace_period: 
  sysctls: 
  userns_mode: 
  autodestroy: 
  autoredeploy: 
  deployment_strategy: 
  sequential_deployment: 
  tags: 
  target_num_containers: 
  roles: 
volumes:
networks:
secrets:

non_sort:
  entrypoint:
  command:
  test: